baseURL = 'https://corpus-tools.org/'
languageCode = 'en-us'
title = 'corpus-tools.org'
theme = "hugo-theme-monochrome"


[params]
hide_navbar_on_scroll = false
toc_position = "right"

[params.list_layout]
enable_group_by_year = false
enable_show_date = false
