name: Check for new ANNIS release
on:
  push:
    branches:
      - master
  schedule:
     - cron: "0 7 * * *"
jobs:
  update-annis-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Fetch Latest ANNIS Release
        id: release
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          repo_path: korpling/ANNIS
      - name: Remove "v" prefix from version
        uses: frabert/replace-string-action@v2.5
        id: version
        with:
          pattern: 'v(.+)'
          replace-with: '$1'
          string: ${{ steps.release.outputs.tag_name  }}
      - name: Prepare short-version
        uses: frabert/replace-string-action@v2.5
        id: short-version
        with:
          pattern: '([0-9]+\.[0-9]+)\.[0-9]+'
          replace-with: '$1'
          string: ${{ steps.version.outputs.replaced }}
      - name: Replace version file
        uses: DamianReeves/write-file-action@v1.0
        if: ${{ !startsWith(steps.version.outputs.replaced , 'annis-') }}
        with:
          path: _data/annis.yml
          contents: |
            version: "${{ steps.version.outputs.replaced }}"
            short-version: "${{ steps.short-version.outputs.replaced }}"
          write-mode: overwrite
      - name: Replace release notes
        uses: DamianReeves/write-file-action@v1.3
        if: ${{ !startsWith(steps.version.outputs.replaced , 'annis-') }}
        with:
          path: _includes/annis-release-notes.md
          contents: ${{ steps.release.outputs.body  }}
          write-mode: overwrite
      - run: git add _data/annis.yml _includes/annis-release-notes.md
        if: ${{ !startsWith(steps.version.outputs.replaced , 'annis-') }}
      - run: git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "New ANNIS version ${{ github.event.client_payload.version }} released" || true
        if: ${{ !startsWith(steps.version.outputs.replaced , 'annis-') }}
      - name: Push changes
        if: ${{ !startsWith(steps.version.outputs.replaced , 'annis-') }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
