name: Check for new ANNIS release
on:
  schedule:
     - cron: "29 21 * * *"
jobs:
  update-annis-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Fetch Latest ANNIS Release
        id: release
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          repo_path: korpling/ANNIS
      - name: Remove "v" prefix from version
        uses: frabert/replace-string-action@v2.0
        id: version
        with:
          pattern: 'v(.+)'
          replace-with: '$1'
          string: ${{ steps.release.outputs.tag_name  }}
      - name: Prepare short-version
        uses: frabert/replace-string-action@v2.0
        id: short-version
        with:
          pattern: '([0-9]+\.[0-9]+)\.[0-9]+'
          replace-with: '$1'
          string: ${{ steps.version.outputs.replaced }}
      - name: Replace long version
        uses: mingjun97/file-regex-replace@v1
        with:
           regex: '"version": ([0-9\.]*),'
           replacement: '"version": ${{ steps.version.outputs.replaced }},'
           include: 'annis\.yml'
           path: '_data'
      - name: Replace short version
        uses: mingjun97/file-regex-replace@v1
        with:
           regex: '"short-version": ([0-9\.]*),'
           replacement: '"short-version": ${{ steps.short-version.outputs.replaced }},'
           include: 'annis\.yml'
           path: '_data'
      - name: Replace release notes
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: _includes/annis-release-notes.md
          contents: ${{ steps.release.outputs.body  }}
          write-mode: overwrite
      - run: git add _data/annis.yml _includes/annis-release-notes.md
      - run: git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "New ANNIS version ${{ github.event.client_payload.version }} released" || true
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
